apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-kube-prometheus-prometheus-0
  namespace: default
spec:
  type: NodePort
  selector:
    app: prometheus-prometheus-kube-prometheus-prometheus-0
  ports:
    - protocol: TCP
      port: 9090           # Внутренний порт сервиса
      targetPort: 9090     # Порт, используемый контейнером
      nodePort: 30090      # Статический порт на узле
